In [1]:
import numpy as np
 
class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
        
    def activation_fn(self, x):
        return 1 if x >= 0 else 0
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

In [2]:

if __name__ == '__main__':
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

In [3]:
d = np.array([0, 0, 0, 1])
 
perceptron = Perceptron(input_size=2)
perceptron.fit(X, d)
print(perceptron.W)

[-3.  2.  1.]


In [4]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
d

array([0, 0, 0, 1])

In [6]:
mp = Perceptron(5) #(100*100)
x = np.asarray([-10,-2,-30,-4,-50])
mp.predict(x)

1

In [7]:
mp.activation_fn(10)

1

In [8]:
mp.W

array([0., 0., 0., 0., 0., 0.])

1- Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız.
   
   init :  
Perceptron oluşturur. İlk olarak kaç veri olacağını kullanıcıdan girdi olarak alırız. Sapmayı dahil etmek için girdi boyutunu arttırırız.

   activation_fn:
Toplam foksiyonundan elde ettiğimiz değeri aktivasyon fonksiyonuna parametre olarak göndeririz. ">0" ise 1, "<0" ise 0 olacak şekilde aktivasyonu fonksiyonu  çıktı üretmiş olur.

   predict:
Tahmin fonksiyonu olup girdiler sonucu çıktı üretmeyi sağlar. Bias değeri eklendikten sonra "dot" metodu ile 2 dizinin çarpımı gerçekleştirilir(input ve ağırlık). Bu değer activation_fn gönderilir ve bir çıktı elde edilir.

   fit:
Eğitim fonksiyonudur. Girdiler kullanıcıdan alınır ve bunlar üzerinde herhangi bir değişim gerçekleştirilemez. Fakat W (ağırlık değerleri) ve b değerleri problemin çözümüne katkı sağlayacak şekilde değiştirilebilir. Bu fonksiyonda iteratif olarak W ve b değerlerinin güncellenmesini sağlar. Tahmin değerini oluşturup hata hesaplamasını yapabilir.


2- XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.  

Aşağıda gösterildiği gibi predict fonksiyonu doğru sonuçları üretmemekte. And ve Or işlemlerinde bu tür sorunlar yaşanmıyordu. Çünkü predict fonksiyonu  doğrusal olarak ayrılabilen çıktılarda doğru çalışırken, Xor gibi doğrusal ayrılamayan problemlerde yanlış çalışıyor.


In [21]:

if __name__ == '__main__':
    X = np.array([  #X girdiler
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
    d = np.array([0, 1, 1, 0]) #girdilere uygun output değerleri -> d
 
    perceptron = Perceptron(input_size=2)
    perceptron.fit(X, d)
    print(perceptron.W)
    
    #predict fonksiyonu sonucu hesaplanan değerler
    print(perceptron.predict(np.asarray([0,0]))) #1
    print(perceptron.predict(np.asarray([0,1]))) #1
    print(perceptron.predict(np.asarray([1,0]))) #0
    print(perceptron.predict(np.asarray([1,1]))) #0
    
     

[ 0. -1.  0.]
1
1
0
0


3- bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız

Yukarıdaki kodun yorum satırlarında da gösterildiği gibi X inputları, d ise beklenen outputları ifade etmekte. 40 öğrenci olduğundan, öğrenci imzalarını tutacak 40 elemanlı bir diziye ihtiyaç vardır => X değeri. Her bir öğrencinin imza karşılığı 40 adettir => d değeri. 

Predict fonksiyonunun girdisi olarak öğrenci imzası verilir. Girdiler işlenir ve sonucunda imzanın kime ait olduğu bilgisi output olarak elde edilir 

4- Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız.

Elde ettiğimiz çıktıdan asıl beklediğimiz sonucu çıkarttığımızda hatayı elde edebiliriz. Daha sonra gerekli iyileştirmeler yapılabilir. Ve bu hata değeri 0 çıkana kadar ya da belirlenen bir limit değerinden sonra sonlandırılabilir.